#!/bin/sh

[ "${ACTION}" = "released" ] || exit 0

. /lib/functions.sh

logger "$BUTTON pressed for $SEEN seconds"

if [ "$SEEN" -lt 1 ]
then
	echo "REBOOT" > /dev/console
	#Stop all valves on reboot
	for i in $(seq 40 47); do echo 0 > /sys/class/gpio/gpio$i/value; done
	#Close wlan led
	echo 0 > /sys/class/leds/rainmachine:wlan/brightness
	#Close the rest of the leds
	for i in $(seq 0 15); do echo 0 > /sys/class/leds/rm-$i/brightness; done
	#Light up the - middle segment of the number led
	echo 80 > /sys/class/leds/rm-0/brightness
	sync
	reboot
elif [ "$SEEN" -gt 3 -a "$SEEN" -lt 13 ]
then
	echo "FACTORY RESET" > /dev/console
	#Beep
	echo 1 > /sys/class/gpio/gpio12/value
	sleep 1
	echo 0 > /sys/class/gpio/gpio12/value
	#Blink leds
	#for i in $(seq 0 15); do echo timer > /sys/class/leds/rm-$i/trigger; done
	#Close wlan led
	echo 0 > /sys/class/leds/rainmachine:wlan/brightness
	#Close the rest of the leds
	for i in $(seq 0 15); do echo 0 > /sys/class/leds/rm-$i/brightness; done
	#Reboot animation
	/usr/sbin/rainmachine-led-anim /etc/rainmachine-boot-animation.conf &
	touch /tmp/factory-reset
elif [ "$SEEN" -gt 14 ]
then
	echo "RESET TO DEFAULTS" > /dev/console
        #Beep
        echo 12 > /sys/class/gpio/gpio12/value
        sleep 1 
        echo 0 > /sys/class/gpio/gpio12/value
        echo 12 > /sys/class/gpio/gpio12/value
        sleep 1
        echo 0 > /sys/class/gpio/gpio12/value
        rm -rvf /rainmachine-app/DB/
	sync
	reboot
fi
